version: '3'

tasks:
  default:
    cmds:
      - task: test-all
  test-all:
    desc: Run all tests
    cmds:
      - go test {{.CLI_ARGS}} ./...
  test:
    desc: Run a specific test
    cmds:
      - go test {{.CLI_ARGS}}
  run:
    desc: Run the executable
    cmds:
      - go run . {{.CLI_ARGS}}
  build:
    desc: Compile the binary
    cmds:
      - go build -o aoc .
  fmt:
    desc: Format the code, ensuring that lines don't exceed 70 char
    cmds:
      - golines --shorten-comments --chain-split-dots --max-len=70 -w **/*.go
  doc-server:
    desc: Start the doc server
    cmds:
      - pkgsite -http=:6060